<a href="https://colab.research.google.com/github/S5432/Gen_AI_Practice/blob/main/GanAI_Text_classification_ML_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Text Classification**

In [12]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics import confusion_matrix
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)
pd.set_option('display.max_colwidth',255)


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [13]:
df  = pd.read_csv(r'/content/IMDB Dataset.csv')

In [14]:
df.head()

review  \
0  One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of v...   
1  A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen-...   
2  I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well b...   
3  Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br...   
4  Petter Mattei's "Love in the Time of Money" is a visually stunning film to watch. Mr. Mattei offers us a vivid portrait about human relations. This is a movie that seems to be telling us what money, power and success do to people in the different situ...   

  sentiment  
0  positive  
1  positive  
2  positive  
3  negative  
4  positive

In [15]:
df.shape

(50000, 2)

In [16]:
df = df.head(10000)

In [18]:
# take only 20% data
df.shape

(10000, 2)

In [19]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [20]:
df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [21]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [22]:
df.duplicated().sum()

17

In [23]:
df.drop_duplicates(inplace=True)

In [24]:
df.duplicated().sum()

0

# **Using Basic Preprocessing Technique**

- Remove HTML tags
- Lower case
- Remove stopwords

In [25]:
import re
def remove_tag(raw_text):
  cleaned_text = re.sub(re.compile('<.*?>'),'',raw_text)
  return cleaned_text

In [26]:
df['review'] = df['review'].apply(remove_tag)

In [27]:
df.head()

review  \
0  One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.The first thing that struck me about Oz was its brutality and unflinching scenes of violence, whi...   
1  A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only ...   
2  I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well b...   
3  Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.OK, first of al...   
4  Petter Mattei's "Love in the Time of Money" is a visually stunning film to watch. Mr. Mattei offers us a vivid portrait about human relations. This is a movie that seems to be telling us what money, power and success do to people in the different situ...   

  sentiment  
0  positive  
1  positive  
2  positive  
3  negative  
4  positive

#lowercase

In [28]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.I would say the main appeal of the show is due to the fact that it goes where other shows wo

In [31]:
df['review'] =df['review'].str.lower()

In [32]:
df['review'][0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wo

In [33]:
df['review'].head()

0    one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, whi...
1    a wonderful little production. the filming technique is very unassuming- very old-time-bbc fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. the actors are extremely well chosen- michael sheen not only ...
2    i thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. the plot is simplistic, but the dialogue is witty and the characters are likable (even the well b...
3    basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.ok, first of al...
4    petter mattei's "love in the time of money" is a visually stunning film to watch. mr. mattei offers us a vivid portrait about human relations. this is a movie that seems to be telling us what money, power and success do to people in the different situ...
Name: review, dtype: object

# remove stopwords

In [35]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [36]:
sw_list = stopwords.words('english')


In [37]:
len(sw_list)

179

In [38]:
df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))


In [39]:
df['review'][0]

"one reviewers mentioned watching 1 oz episode hooked. right, exactly happened me.the first thing struck oz brutality unflinching scenes violence, set right word go. trust me, show faint hearted timid. show pulls punches regards drugs, sex violence. hardcore, classic use word.it called oz nickname given oswald maximum security state penitentary. focuses mainly emerald city, experimental section prison cells glass fronts face inwards, privacy high agenda. em city home many..aryans, muslims, gangstas, latinos, christians, italians, irish more....so scuffles, death stares, dodgy dealings shady agreements never far away.i would say main appeal show due fact goes shows dare. forget pretty pictures painted mainstream audiences, forget charm, forget romance...oz mess around. first episode ever saw struck nasty surreal, say ready it, watched more, developed taste oz, got accustomed high levels graphic violence. violence, injustice (crooked guards who'll sold nickel, inmates who'll kill order g

# Seperate the data into input and output

In [41]:
x = df['review']
y = df['sentiment']

In [42]:
x.head()

0    one reviewers mentioned watching 1 oz episode hooked. right, exactly happened me.the first thing struck oz brutality unflinching scenes violence, set right word go. trust me, show faint hearted timid. show pulls punches regards drugs, sex violence. ha...
1    wonderful little production. filming technique unassuming- old-time-bbc fashion gives comforting, sometimes discomforting, sense realism entire piece. actors extremely well chosen- michael sheen "has got polari" voices pat too! truly see seamless edit...
2    thought wonderful way spend time hot summer weekend, sitting air conditioned theater watching light-hearted comedy. plot simplistic, dialogue witty characters likable (even well bread suspected serial killer). may disappointed realize match point 2: r...
3    basically there's family little boy (jake) thinks there's zombie closet & parents fighting time.this movie slower soap opera... suddenly, jake decides become rambo kill zombie.ok, first going make film must decide thriller drama! drama movie watchable...
4    petter mattei's "love time money" visually stunning film watch. mr. mattei offers us vivid portrait human relations. movie seems telling us money, power success people different situations encounter. variation arthur schnitzler's play theme, director ...
Name: review, dtype: object

In [43]:
y.head()

0    positive
1    positive
2    positive
3    negative
4    positive
Name: sentiment, dtype: object

# **Labelencoder**

# Output column data is in text formate(Positive/Negative/True/False) and so we use Labelencoder to convert in 0,1

In [44]:
from sklearn.preprocessing import LabelEncoder

In [45]:
encoder = LabelEncoder()

In [46]:
y = encoder.fit_transform(y)

In [48]:
y

array([1, 1, 1, ..., 0, 0, 1])

#model_selection

In [49]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [50]:
x_train.shape

(7986,)

In [51]:
x_test.shape

(1997,)

# Now Applying the BOG
- Bag of words

In [52]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [54]:
x_train_bow = cv.fit_transform(x_train).toarray()
x_test_bow = cv.transform(x_test).toarray()

In [55]:
x_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [56]:
x_test_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# Round 1 to check the model performance by using ML algorithms.

In [57]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [58]:
gnb.fit(x_train_bow,y_train)

GaussianNB()

In [60]:

y_pred = gnb.predict(x_test_bow)

- now check the accuracy score

In [61]:
from sklearn.metrics import accuracy_score,confusion_matrix


In [62]:
accuracy_score(y_test,y_pred)

0.627941912869304

In [63]:
confusion_matrix(y_test,y_pred)

array([[694, 291],
       [452, 560]])

- using deffirent ML algorithms

#RandomForestClassifier

In [64]:
from sklearn.ensemble import RandomForestClassifier

In [65]:
rf = RandomForestClassifier()

In [67]:
rf.fit(x_train_bow,y_train)

RandomForestClassifier()

In [77]:
y_pred = rf.predict(x_test_bow)

In [69]:
accuracy_score(y_test,y_pred)

0.8482724086129194

- Use hyper parameter
- max_features =3000
- we take 3000 vocabulary means unique words with high freequency.

In [70]:
cv = CountVectorizer(max_features=3000)

In [72]:
x_train_bow = cv.fit_transform(x_train).toarray()
x_test_bow = cv.transform(x_test).toarray()

In [73]:
rf = RandomForestClassifier()

In [74]:
rf.fit(x_train_bow,y_train)

RandomForestClassifier()

In [78]:
y_pred = rf.predict(x_test_bow)

In [79]:
accuracy_score(y_test,y_pred)

0.828743114672008

# Use N grams to improve The model accuracy

In [80]:
cv = CountVectorizer(ngram_range=(2,2), max_features=5000)

x_train_bow = cv.fit_transform(x_train).toarray()
x_test_bow = cv.transform(x_test).toarray()

In [81]:
rf = RandomForestClassifier()

In [82]:
rf.fit(x_train_bow,y_train)

RandomForestClassifier()

In [83]:
y_pred = rf.predict(x_test_bow)

In [84]:
accuracy_score(y_test,y_pred)

0.7431146720080121

# use Tf-idf feature extraction technique

In [85]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [86]:
tfidf = TfidfVectorizer()

In [87]:
x_train_tfidf = tfidf.fit_transform(x_train).toarray()

In [88]:
x_test_tfidf = tfidf.transform(x_test).toarray()

In [89]:
rf = RandomForestClassifier()

In [90]:
rf.fit(x_train_tfidf, y_train)

RandomForestClassifier()

In [91]:
y_pred = rf.predict(x_test_tfidf)

In [92]:
accuracy_score(y_test,y_pred)

0.85728592889334

# Now we use Word2Vec

In [93]:
import gensim

In [94]:
!pip install --upgrade gensim --user

In [99]:
# story = []
# for filename in os.listdir('/content/IMDB Dataset.csv'):
#   if filename == '.ipynb_checkpoints':
#     pass
#   f = open(os.path.join('/content/IMDB Dataset.csv',filename))
#   corpus = f.read()
#   raw_sent = sent_tokenize(corpus)
#   for sent in raw_sent:
#     story.append(simple_preprocess(sent))

In [100]:
import os
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess

# Initialize an empty list to store the processed sentences
story = []

# Path to the file
file_path = '/content/IMDB Dataset.csv'

# Open the file and process its content
with open(file_path, 'r', encoding='utf-8') as f:
    corpus = f.read()  # Read the content of the file
    raw_sent = sent_tokenize(corpus)  # Tokenize the content into sentences
    for sent in raw_sent:
        story.append(simple_preprocess(sent))  # Preprocess each sentence and add to the story list

# Now 'story' will contain the preprocessed sentences


In [101]:
story

[['review',
  'sentiment',
  'one',
  'of',
  'the',
  'other',
  'reviewers',
  'has',
  'mentioned',
  'that',
  'after',
  'watching',
  'just',
  'oz',
  'episode',
  'you',
  'll',
  'be',
  'hooked'],
 ['they',
  'are',
  'right',
  'as',
  'this',
  'is',
  'exactly',
  'what',
  'happened',
  'with',
  'me',
  'br',
  'br',
  'the',
  'first',
  'thing',
  'that',
  'struck',
  'me',
  'about',
  'oz',
  'was',
  'its',
  'brutality',
  'and',
  'unflinching',
  'scenes',
  'of',
  'violence',
  'which',
  'set',
  'in',
  'right',
  'from',
  'the',
  'word',
  'go'],
 ['trust',
  'me',
  'this',
  'is',
  'not',
  'show',
  'for',
  'the',
  'faint',
  'hearted',
  'or',
  'timid'],
 ['this',
  'show',
  'pulls',
  'no',
  'punches',
  'with',
  'regards',
  'to',
  'drugs',
  'sex',
  'or',
  'violence'],
 ['its',
  'is',
  'hardcore',
  'in',
  'the',
  'classic',
  'use',
  'of',
  'the',
  'word',
  'br',
  'br',
  'it',
  'is',
  'called',
  'oz',
  'as',
  'that',
  'is

In [102]:
story[0]

['review',
 'sentiment',
 'one',
 'of',
 'the',
 'other',
 'reviewers',
 'has',
 'mentioned',
 'that',
 'after',
 'watching',
 'just',
 'oz',
 'episode',
 'you',
 'll',
 'be',
 'hooked']

In [104]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [105]:
model.build_vocab(story)

In [106]:
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

(42741179, 56132345)

In [107]:
vec = model.wv.get_normed_vectors()

In [113]:
y = model.wv.index_to_key

In [115]:
y

['the',
 'and',
 'of',
 'to',
 'is',
 'br',
 'it',
 'in',
 'this',
 'that',
 'was',
 'as',
 'movie',
 'for',
 'with',
 'but',
 'film',
 'you',
 'on',
 'not',
 'he',
 'are',
 'his',
 'have',
 'one',
 'be',
 'all',
 'at',
 'they',
 'by',
 'an',
 'who',
 'so',
 'from',
 'like',
 'there',
 'or',
 'just',
 'her',
 'out',
 'about',
 'if',
 'has',
 'what',
 'some',
 'good',
 'can',
 'when',
 'more',
 'very',
 'she',
 'up',
 'positive',
 'negative',
 'no',
 'time',
 'my',
 'even',
 'would',
 'which',
 'only',
 'story',
 'really',
 'see',
 'their',
 'had',
 'me',
 'well',
 'we',
 'were',
 'than',
 'much',
 'bad',
 'get',
 'been',
 'other',
 'do',
 'people',
 'great',
 'will',
 'also',
 'into',
 'because',
 'how',
 'don',
 'him',
 'first',
 'most',
 'made',
 'its',
 'them',
 'then',
 'make',
 'way',
 'could',
 'too',
 'movies',
 'any',
 'after',
 'characters',
 'think',
 'watch',
 'character',
 'films',
 'two',
 'many',
 'seen',
 'being',
 'love',
 'plot',
 'never',
 'life',
 'acting',
 'where',

In [116]:

rf  = RandomForestClassifier()

In [119]:
 x = rf.fit_transform(vec)

AttributeError: 'RandomForestClassifier' object has no attribute 'fit_transform'